<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	
  <PropertyGroup>
	<Title>Arcavis Outbox Abstractions</Title>
    <Description>
        Provider-independent abstractions for the Arcavis Outbox library.
    </Description>
    <Authors>Jurnest</Authors>
    <PackageId>Arcavis.Outbox.Abstractions</PackageId>
    <Version>0.1.0</Version>
    <RepositoryUrl>https://github.com/sigillum-app/Arcavis.Outbox</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="$(MSBuildProjectDirectory)/../../README.md"
		  Pack="true"
		  PackagePath="\" />

	<None Include="$(MSBuildProjectDirectory)/../../LICENSE"
		  Pack="true"
		  PackagePath="\" />
  </ItemGroup>
</Project>
